config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # devise_for :user 
  
  get 'friends', to: 'friends#index'
  get 'users/search', to: 'users#search'
  delete 'friends/destroy'

  resources :friend_requests, except: [:show, :edit, :new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  root to: 'home#index'
  # get 'home/index'
  get 'articles/new', to: 'articles#new'
  get 'articles', to: 'articles#index'
  post 'articles', to: 'articles#create'
  get 'articles/:id', to: 'articles#show', as: 'article'
  patch 'articles/:id', to: 'articles#update'
  delete 'articles/:id', to: 'articles#destroy'
  get 'articles/:id/edit', to: 'articles#edit', as: 'article_edit'

  resources :users, except: [:index] do 
    member do
      get :confirm_email
      get :change_password
      patch :change_password_confirm
    end
  end

  post 'comments/:id/edit', to: 'comments#create'
  get 'comments/:id/edit', to: 'comments#edit', as: 'comment_edit'
  patch 'comments/:id/edit', to: 'comments#update'
  delete 'comments/:id/edit', to: 'comments#destroy'

  resources :groups do 
    resources :group_articles, :path => "articles", :as => "articles"
  end

  resources :group_comments, only: [:create, :edit, :update, :destroy]

  delete 'groups/:id/leave', to: 'groups#leave_group', as: 'leave_group'

end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, :content, presence: true
    has_many :comments, dependent: :destroy
    belongs_to :user
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :authorize_article, only: [:new, :create]
    after_action :verify_authorized, except: [:index]

    def index
        @articles = Article.all.includes(:user)
    end

    def show
        @user = User.find_by_id(@article.user_id)
        @comment = Comment.new
        @comments = Comment.where(article_id: params[:id]).includes(:user)
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        @article.user_id = session[:user_id]
        if @article.save
            redirect_to @article, flash: {success: "Article was created."}
        else
            render 'new'
        end
        
    end

    def edit
    end

    def update
        if @article.update(article_params)
            redirect_to article_path(@article.id)
        else
            render 'edit'
        end
    end

    def destroy
        if @article
            @article.destroy
            redirect_to articles_path, flash: {success: "Article was deleted."}
        else
            render 'show'
        end
    end

private

    def article_params
        params.require(:article).permit(:title, :content)
    end

    def set_article
        @article = Article.find(params[:id])
        authorize @article
    end

    def authorize_article
        authorize Article
    end

end

app/helpers/articles_helper.rb
module ArticlesHelper

    def can_edit_delete?(user)
        logged_in? && current_user == user
    end
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
    <div class="ui error message">
        <ul>
            <% @article.errors.full_messages.each do |e| %>
                <li><%= e %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<%= form_for @article do |form| %>
    <div class="ui form">
        <div class="field">
            <%= form.label :title %>
            <%= form.text_field :title, placeholder: "Enter your title here", autofocus: true %>
        </div>

        <div class="field">
            <%= form.label :content %>
            <%= form.text_area :content, {size: "60x10", placeholder: "Enter the contents of your article here"} %>
        </div>

        <% if params[:action] == 'edit' %>
            <%= form.submit 'Update', :class=>"ui blue button" %>
        <% else %>
            <%= form.submit 'Create', :class=>"ui green button" %>
        <% end %>
    </div>
<% end %>

app/views/articles/_writtenby.html.erb
<div class="ui segment">
    Written by <%= link_to @user.username, @user %> on <%= @article.created_at.strftime("%B %-d, %Y") %>
    <div>
        <% if @article.created_at != @article.updated_at %>
            Last updated on <%= @article.updated_at.strftime("%B %-d, %Y") %>
        <% end %>
    </div>
</div>

app/views/articles/edit.html.erb
<h2>Edit this Article
    <%= render 'shared/back_button', path: article_path(@article) %>
</h2>
<%= render :partial => "form" %>

app/views/articles/index.html.erb
<h1>
    Article Listing (<%= @articles.length %>)
    <% if logged_in? %>
        <span class="align-right">
            <%= button_to 'New', articles_new_path, method: :get, :class=>"ui button green",
                params: {action: 'create'} %>
        </span>
    <% end %>
</h1>

<ul>
    <div class="ui divider"></div>
    <% @articles.each do |a| %>
        <li>
            <%= link_to(a.title, article_path(a.id)) %>
            <span class="align-right">
                <%= a.user.username %>
            </span>
        </li>
        <div class="ui divider"></div>
    <% end %>
</ul>

app/views/articles/new.html.erb
<h2>Create your Article
    <%= render 'shared/back_button', path: articles_path %>
</h2>
<%= render :partial => "form" %>

app/views/articles/show.html.erb
<h2><%= @article.title %>
    <%= render 'shared/back_button', path: articles_path %>
</h2>


<%= render partial: 'writtenby' %>

<br>
<div class="article-body" style="white-space: pre-wrap;"><%= simple_format(@article.content) %></div>
<br>
<div class="ui divider"></div>

<div>
    <h4>Comments</h4>
    <ul>
        <% if @comments.any? %>
            <% @comments.each do |comment| %>
                <li>
                    <%= comment.content %>
                     – <%= link_to comment.user.username, user_path(comment.user) %>
                    <% if can_edit_delete?(comment.user) %>
                        (
                        <%= link_to 'Edit', comment_edit_path(comment, comment_id: comment.id) %>
                        | 
                        <%= link_to 'Delete', comment_edit_path(comment, comment_id: comment.id), method: :delete,
                            article_id: @article.id,
                            data: { confirm: 'Are you sure you want to delete this comment? This action cannot be undone.' } %>
                        )
                    <% end %>
                </li>
            <% end %>
        <% else %>
            <p>No comments yet. Why don't you be the first to comment?</p>
        <% end %>
    </ul>
</div>


<div class="ui divider"></div>

<%= render partial: 'comments/form' %>

<% if can_edit_delete?(@user) %>
    <div class="ui divider"></div>
    <%= button_to "Edit this article", article_edit_path(@article.id),
        :class=>"ui button blue", method: :get, params: {action: 'edit'} %>
    <br>
    <%= button_to "Delete this article", article_path(@article.id),
        :class=>"ui button red", method: :delete,
        data: { confirm: 'Are you sure you want to delete this article? This action cannot be undone.' } %>
<% end %>