config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # devise_for :user 
  
  get 'friends', to: 'friends#index'
  get 'users/search', to: 'users#search'
  delete 'friends/destroy'

  resources :friend_requests, except: [:show, :edit, :new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  root to: 'home#index'
  # get 'home/index'
  get 'articles/new', to: 'articles#new'
  get 'articles', to: 'articles#index'
  post 'articles', to: 'articles#create'
  get 'articles/:id', to: 'articles#show', as: 'article'
  patch 'articles/:id', to: 'articles#update'
  delete 'articles/:id', to: 'articles#destroy'
  get 'articles/:id/edit', to: 'articles#edit', as: 'article_edit'

  resources :users, except: [:index] do 
    member do
      get :confirm_email
      get :change_password
      patch :change_password_confirm
    end
  end

  post 'comments/:id/edit', to: 'comments#create'
  get 'comments/:id/edit', to: 'comments#edit', as: 'comment_edit'
  patch 'comments/:id/edit', to: 'comments#update'
  delete 'comments/:id/edit', to: 'comments#destroy'

  resources :groups do 
    resources :group_articles, :path => "articles", :as => "articles"
  end

  resources :group_comments, only: [:create, :edit, :update, :destroy]

  delete 'groups/:id/leave', to: 'groups#leave_group', as: 'leave_group'

end

app/models/group.rb
class Group < ApplicationRecord
    validates :name, :description, :item_name, :creator, presence: true
    validates :name, uniqueness: {:scope => :creator }
    has_and_belongs_to_many :users, :join_table => :users_groups, dependent: :destroy
    belongs_to :creator, class_name: 'User', foreign_key: :user_id
    has_many :group_articles, dependent: :destroy
    has_many :group_comments
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    before_action :set_group, only: [:show, :edit, :update, :destroy, :leave_group]
    before_action :authorize_group, only: [:new, :create, :index]

    def new
        @group = Group.new
        if logged_in?
            @friends = current_user.friends
        end
    end

    def create
        @group = Group.new(group_params) 
        @group.user_id = session[:user_id]
        @group.creator = current_user
        if @group.item_name.strip == ""
            @group.item_name = "Article"
        end

        max_group_size = 5
        @group.users << current_user
        if params[:friends] != nil
            if params[:friends].length > max_group_size
                @friends = current_user.friends
                flash.now[:error] = "You can only add up to 5 friends in a group."
                render 'new'
                return
            end

            params[:friends].each do |f| 
                @group.users << User.find_by_username(f)
            end
        end

        if @group.save
            redirect_to groups_path(@group), flash: {success: "Group was created."}
        else
            @friends = current_user.friends
            render 'new'
        end
    end

    def index
        @groups = current_user.groups.includes(:creator)
        authorize @groups
    end

    def show
        @articles = @group.group_articles.includes(:user)
    end

    def edit
        if logged_in?
            @friends = current_user.friends
        end
    end

    def update
        max_group_size = 5

        @users_to_remove = []
        @users_to_add = []

        if params[:friends] == nil
            @group.users.each do |u|
                if u != current_user
                    @users_to_remove << u
                end
            end
        else
            if params[:friends].length > max_group_size
                @friends = current_user.friends
                redirect_to edit_group_path(@group), flash: {error: "You can only add up to 5 friends in a group."}
                return
            end

            @group.users.each do |u|
                if !params[:friends].include?(u.username) && u != current_user
                    @users_to_remove << u
                end
            end

            params[:friends].each do |f|
                if !@group.users.find_by_username(f)
                    @users_to_add << User.find_by_username(f)
                end
            end
        end 

        if @group.update(group_params)
            if @users_to_remove
                @group.users.delete(@users_to_remove)
            end

            if @users_to_add
                @users_to_add.each do |u|
                    @group.users << u
                end
            end

            redirect_to group_path(@group), flash: {success: "Group was updated."}

        else
            @friends = current_user.friends
            render 'edit'
        end
    end

    def destroy
        if @group
            @group.destroy
            redirect_to groups_path, flash: {success: "Group was deleted."}
        else
            render 'index'
        end
    end

    def leave_group
        @group.users.destroy(current_user)
        redirect_to groups_path, flash: {success: "You have been removed from the group."}
    end

private

    def group_params
        params.require(:group).permit(:name, :description, :item_name, :user_id, :creator)
    end

    def set_group
        @group = Group.find(params[:id])
        authorize @group
    end

    def authorize_group
        authorize Group
    end

end

app/helpers/groups_helper.rb
module GroupsHelper

    def is_creator?(group)
        group.creator == current_user
    end

    def current_group

    end

end

app/views/groups/_group_form.html.erb
<%= form_for @group do |g| %>
    <div class="ui form">
        <div class="field">
            <%= g.label :name %>
            <%= g.text_field :name, :placeholder=>"Give your group an easily recognizable name.",
                autofocus: true %>
        </div>
        <div class="field">
            <%= g.label :description %>
            <%= g.text_area :description, :size=>"60x3", :placeholder=>"Let others know what your group is about." %>
        </div>
        <div class="field">
            <%= g.label :item_name, 'Counter for posts' %>
            <p>The term used to refer to posts made in the group. The default is "Article".</p>
            <%= g.text_field :item_name, :value=>"Article", :placeholder=>'If blank, this will default to "Article"' %>
        </div>

        <br>

        <div class="field">
            <%= g.label :users, 'Friends to Include (Up to 5)' %>
            <div class="ui divider"></div>
            <% if @friends %>
                <% @friends.each do |f| %>
                    <div class="ui toggle checkbox">
                        <%= check_box_tag 'friends[]', f.username %>
                        <label><%= f.username %></label>
                    </div>
                    <div class="ui divider"></div>
                <% end %>
            <% end %>
        </div>
        
        <br>

        <div class="field">
            <%= g.button "Create Group", :class=>"ui button green" %>
        </div>
    </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Edit Group
    <%= render 'shared/back_button', path: group_path(@group) %>
</h1>
<p>Edit your group as you see fit.</p>

<%= render 'shared/errors', obj: @group %>

<%= form_for(@group) do |g| %>
    <div class="ui form">
        <div class="field">
            <%= g.label :name %>
            <%= g.text_field :name, :placeholder=>"Give your group an easily recognizable name.", :required=>"required" %>
        </div>
        <div class="field">
            <%= g.label :description %>
            <%= g.text_area :description, :size=>"60x3", :placeholder=>"Let others know what your group is about." %>
        </div>
        <div class="field">
            <%= g.label :item_name, 'Counter for posts' %>
            <p>The term used to refer to posts made in the group. The default is "Article".</p>
            <%= g.text_field :item_name, :placeholder=>'If blank, this will default to "Article"' %>
        </div>

        <br>

        <div class="field">
            <%= g.label :users, 'Friends to Include (Up to 5)' %>
            <div class="ui divider"></div>
            <% if @friends %>
                <% @friends.each do |f| %>
                    <div class="ui toggle checkbox">
                        <%= check_box_tag 'friends[]', f.username, checked = (@group.users.find_by(id: f.id)) %>
                        <label><%= f.username %></label>
                    </div>
                    <div class="ui divider"></div>
                <% end %>
            <% end %>
        </div>
        
        <br>

        <div class="field">
            <%= g.button "Update Group", :class=>"ui button blue", method: :patch %>
        </div>
    </div>
<% end %>

app/views/groups/index.html.erb
<h1><span class="user-info"><%= current_user.username %></span>'s Groups (<%= @groups.length %>)
    <% if logged_in? %>
        <span class="align-right">
            <%= button_to "New Group", new_group_path, :class=>"ui button green",
                method: :get %>
        </span>
    <% end %>
</h1>


<% if !@groups.empty? %>
    <ul>
        <% @groups.each do |g| %>
            <div class="ui segment">
            <%= link_to g.name, group_path(g) %>
            <span class="align-right">
                Creator: <%= link_to g.creator.username, g.creator %>
            </span>
            </div>
        <% end %>
    </ul>
<% else %>
    <div class="ui divider"></div>
    <p>It looks like you aren't involved in any groups. Why not start one?</p>
<% end %>

app/views/groups/new.html.erb
<h1>New Group
    <%= render 'shared/back_button', path: groups_path %>
</h1>
<p>Enter all fields below to create a group.</p>

<%= render 'shared/errors', obj: @group %>

<%= render 'group_form' %>

app/views/groups/show.html.erb
<h1>
    <%= @group.name %>
    <%= render 'shared/back_button', path: groups_path %>
    <% if is_creator?(@group) %>
        <span class="align-right">
            <%= button_to 'Edit', edit_group_path, method: :get, :class=>"ui button blue",
                params: {group_id: @group.id}  %>
        </span>
    <% end %> 
</h1>

<p>This group was created by <%= link_to @group.creator.username, @group.creator %> on 
    <%= @group.created_at.strftime("%B %-d, %Y") %>
</p>

<div class="ui piled segment">
  <h4 class="ui header">Description</h4>
    <p><%= simple_format(@group.description) %></p>
</div>

<div class="ui divider"></div>

<h3><%= @group.item_name %> List (<%= @group.group_articles.length %>)
    <span class="align-right">
        <%= button_to 'New', new_group_article_path(@group), method: :get, :class=>"ui button green",
            params: {action: 'create'} %>
    </span>
</h3>

<div style="height:1px;font-size:1px;"></div>

<ul>
    <div class="ui divider"></div>
    <% if @articles %>
        <% @articles.each do |a| %>
            <li>
                <%= link_to(a.title, group_article_path(@group, a)) %>
                <span class="align-right">
                    <%= link_to a.user.username, a.user %>
                </span>
            </li>
            <div class="ui divider"></div>
        <% end %>
    <% end %>
</ul>

<div style="height:1px;font-size:1px;"></div>

<h3>Group Members (<%= @group.users.length %>)</h3>

<ul>
    <div class="ui divider"></div>
    <% @group.users.each do |member| %>
        <li>
            <%= link_to member.username, member %>
        </li>
        <div class="ui divider"></div>
    <% end %>
</ul>

<div style="height:1px;font-size:1px;"></div>

<% if is_creator?(@group) %>
    <h3>Manage the Group</h3>
    <div class="ui divider"></div>
    <%= button_to 'Delete this group', group_path(@group), method: :delete, :class=>"ui button red",
        data: {confirm: 'Are you sure you would like to delete this group? All articles and comments associated with this group will be destroyed. This action cannot be undone.'}  %>
<% else %>
    <h3>Manage your status in this group</h3>
    <div class="ui divider"></div>
    <%= button_to 'Leave this group', leave_group_path(@group), method: :delete, :class=>"ui button red",
        data: {confirm: 'Are you sure you would like to leave this group? You will no longer be able to participate in this group. This action cannot be undone.'}  %>
<% end %>