config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # devise_for :user 
  
  get 'friends', to: 'friends#index'
  get 'users/search', to: 'users#search'
  delete 'friends/destroy'

  resources :friend_requests, except: [:show, :edit, :new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  root to: 'home#index'
  # get 'home/index'
  get 'articles/new', to: 'articles#new'
  get 'articles', to: 'articles#index'
  post 'articles', to: 'articles#create'
  get 'articles/:id', to: 'articles#show', as: 'article'
  patch 'articles/:id', to: 'articles#update'
  delete 'articles/:id', to: 'articles#destroy'
  get 'articles/:id/edit', to: 'articles#edit', as: 'article_edit'

  resources :users, except: [:index] do 
    member do
      get :confirm_email
      get :change_password
      patch :change_password_confirm
    end
  end

  post 'comments/:id/edit', to: 'comments#create'
  get 'comments/:id/edit', to: 'comments#edit', as: 'comment_edit'
  patch 'comments/:id/edit', to: 'comments#update'
  delete 'comments/:id/edit', to: 'comments#destroy'

  resources :groups do 
    resources :group_articles, :path => "articles", :as => "articles"
  end

  resources :group_comments, only: [:create, :edit, :update, :destroy]

  delete 'groups/:id/leave', to: 'groups#leave_group', as: 'leave_group'

end

app/models/user.rb
class User < ApplicationRecord
    before_create :confirmation_token

    validates :email, :username, presence: true, uniqueness: { case_sensitive: false }
    validates :email, format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/ }
    validates :username, format: {with: /\A[a-zA-Z]+[a-zA-Z0-9'_.]*\z/ }

    validates :password,
        presence: true,
        length: {minimum: 6},
        confirmation: true,
        on: :create

    validates :password,
        allow_nil: true,
        length: {minimum: 6},
        confirmation: true,
        on: :update
    
    has_secure_password

    has_many :articles, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :friend_requests, dependent: :destroy
    has_many :pending_friends, through: :friend_requests, source: :friend

    has_many :friendships, dependent: :destroy
    has_many :friends, through: :friendships
    has_and_belongs_to_many :groups, :join_table => :users_groups


    def except_current_user(users)
        users.reject { |user| user.id == self.id }
    end

    def self.search(param)
        param.strip!
        param.downcase!
        to_send_back = (username_matches(param)).uniq
        return nil unless to_send_back
        to_send_back
    end
      
    def self.username_matches(param)
        matches('username', param)
    end

    def self.matches(field_name, param)
        where("#{field_name} like ?", "%#{param}%")
    end

    def email_activate
        self.email_confirmed = true
        self.confirm_token = nil
        save!(:validate => false)
    end


private

    def confirmation_token
        if self.confirm_token.blank?
            self.confirm_token = SecureRandom.urlsafe_base64.to_s
        end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :params_search_blank?, only: [:search]
	before_action :set_user, only: [:edit, :update, :show, :destroy, 
		:change_password, :change_password_confirm]
	before_action :authorize_user, only: [:new, :create, :search]

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			UserMailer.registration_confirmation(@user).deliver
			redirect_to root_path, flash: {success: "An email has been sent to you. 
				Please access the URL to confirm your email address."}
		else
			flash[:error] = "Something went wrong. Please try again."
			render 'new'
		end
	end

	def edit
	end

	def update
		if @user.update(user_params)
			redirect_to @user, flash: {success: "Profile was updated."}
		else
			render 'edit'
		end
	end

	def destroy
	end

	def show
		if logged_in?
			@friend = @user.friends.include?(current_user)
			@pending = current_user.friend_requests.exists? friend_id: @user.id
			@received = @user.friend_requests.exists? friend_id: current_user.id
		end

		if @pending 
			@friend_request = current_user.friend_requests.find_by_friend_id(@user.id)
		elsif @received
			@friend_request = @user.friend_requests.find_by_friend_id(current_user.id)
		end
	end

	def search
		@search_blank = params_search_blank?
		if params[:search].blank?
			@users = User.all.order(username: "ASC")
		else
			@users = User.order(username: "ASC").search(params[:search])
		end

		@users = current_user.except_current_user(@users)
		flash.now[:error] = "No users match this search criteria" if @users.blank?
	end

	def confirm_email
		user = User.find_by_confirm_token(params[:id])
		if user
			user.email_activate
			UserMailer.with(user: user).welcome_email.deliver_later
			flash[:success] = "Welcome to Gathering of Writers! Your email has been confirmed.
			Please sign in to continue."
			redirect_to login_path
		else
			flash[:error] = "We are sorry to say this, but that user does not exist."
			redirect_to root_path
		end
	end

	def change_password

	end

	def change_password_confirm
		if !params[:user][:current_password].blank?
			@user = User.find_by_id(params[:id])
			if (@user.authenticate(params[:user][:current_password]) == false)
				@user.errors.add(:current_password, " is incorrect.")
				render 'change_password'
			else
				if params[:user][:password].blank?
					@user.errors.add(:password, " cannot be blank.")
					render 'change_password'
				else
					if params[:user][:current_password] != params[:user][:password]
						if @user.update(user_params)
							flash[:success] = "Your password has been successfully changed."
							redirect_to edit_user_path(@user)
						else
							render 'change_password'
						end
					else
						@user.errors.add(:current_password, " and Password cannot be the same.")
						render 'change_password'
					end
				end
			end
		else
			@user.errors.add(:current_password, " cannot be blank.")
			render 'change_password'
		end
	end

private

	def user_params
		params.require(:user).permit(:email, :username, :password, :password_confirmation, :bio)
	end

	def params_search_blank?
		params[:search] == nil || params[:search].strip == ''
	end

	def set_user
		@user = User.find_by_id(params[:id])
		authorize @user
	end

	def authorize_user
        authorize User
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_userlist.html.erb
<ul>
<% if obj %>
    <div class="ui divider"></div>
    <% obj.each do |o| %>
        <li>
            <%= link_to o.username, o %>
        </li>
        <div class="ui divider"></div>
    <% end %>
<% end %>
</ul>

app/views/users/change_password.html.erb
<h1>Edit Password
    <%= render 'shared/back_button', path: edit_user_path(@user) %>
</h1>
<p>You can change your password here. You'll need your current password to do so.</p>

<% if @user.errors.any? %>
    <div class="ui error message">
        <ul>
            <% @user.errors.full_messages.each do |e| %>
                <li><%= e %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<%= form_for(@user, url: change_password_confirm_user_path(@user)) do |f| %>
    <div class="ui form">
        <div class="field">
            <%= f.label :current_password %>
            <%= f.password_field :current_password %>
        </div>
        <div class="field">
            <%= f.label :password %>
            <%= f.password_field :password %>
        </div>
        <div class="field">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation %>
        </div>
        <div class="field">
            <%= f.button 'Save Changes', :class=>"ui blue button" %>
        </div>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Profile
    <%= render 'shared/back_button', path: @user %>
</h1>
<p>Make any necessary changes and save them here.</p>

<% if @user.errors.any? %>
    <div class="ui error message">
        <ul>
            <% @user.errors.full_messages.each do |e| %>
                <li><%= e %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<h4>Email</h4>
<p>　<%= @user.email %></p><br>

<%= form_for(@user) do |f| %>
    <div class="ui form">
        <div class="field">
            <%= f.label :username %>
            <%= f.text_field :username %>
        </div>
        <div class="field">
            <%= f.label :bio %>
            <%= f.text_area :bio, {size: "60x10", placeholder: "Tell everyone a little about yourself!"} %>
        </div>
        <div class="field">
            <%= f.button 'Save Changes', :class=>"ui blue button" %>
        </div>
    </div>
<% end %>
<br>

<h3>Manage Password</h3>
<div class="ui divider"></div>
<%= button_to "Change Password", change_password_user_path(@user), :class=>"ui button blue",
    method: :get %>

app/views/users/new.html.erb
<h1>User Sign Up</h1>
<p>Enter all fields below and click the "Sign Up" button to proceed.</p>

<%= render 'shared/errors', obj: @user %>

<%= form_for(@user) do |f| %>
    <div class="ui form">
        <div class="field">
            <%= f.label :email %>
            <%= f.email_field :email %>
        </div>
        <div class="field">
            <%= f.label :username %>
            <%= f.text_field :username %>
        </div>
        <div class="field">
            <%= f.label :password %>
            <%= f.password_field :password %>
        </div>
        <div class="field">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation %>
        </div>
        <div class="field">
            <%= f.button 'Sign Up', :class=>"ui green button" %>
        </div>
    </div>
<% end %>

app/views/users/search.html.erb
<h1>Find a User
    <%= render 'shared/back_button', path: friends_path %>
</h1>

<%= form_tag(users_search_path, :method => 'get') do %>
    <div class="ui fluid category search">
        <div class="ui icon input">
            <%= text_field_tag :search, params[:search], placeholder: "Enter username", autofocus: true %>
        </div>
            <%= submit_tag 'Search', :name => nil, :class => "ui button green" %>
    </div>
<% end %>

<div class="ui segment">
    <% if @search_blank %>
        Displaying all users
    <% else %>
        Displaying users that match "<%= params[:search] %>"
    <% end %>
</div>

<%= render 'userlist', obj: @users %>

app/views/users/show.html.erb
<h1><span class="user-info"><%= @user.username %></span>'s Page
    <% if logged_in? && current_user == @user %>
        <span class="align-right">
            <%= button_to "Edit Profile", edit_user_path(@user), :class=>"ui button blue",
                method: :get %>
        </span>
    <% end %>
</h1>

<div class="ui piled segment">
  <h4 class="ui header">Bio</h4>
    <p><%= simple_format(@user.bio) %></p>
</div>

<div class="ui divider"></div>

<div>
    <% if logged_in? %>
        <% if current_user != @user && !@pending && !@received && !@friend %>
            <%= button_to "Send friend request", friend_requests_path, :class=>"ui button green",
                params: {friend_id: @user.id} %>
        <% elsif current_user != @user && @pending && !@received && !@friend %>
            <%= button_to "Cancel friend request", friend_request_path(@friend_request), :class=>"ui button gray",
                method: :delete, data: {confirm: "Are you sure you would like to cancel this friend request? You can send a request again after canceling."} %>
        <% elsif current_user != @user && !@pending && @received && !@friend %>
            <%= button_to "Accept friend request", friend_request_path(@friend_request), :class=>"ui button blue",
                method: :patch %>
            <%= button_to "Decline friend request", friend_request_path(@friend_request), :class=>"ui button red",
                method: :delete, data: {confirm: "Are you sure you would like to decline this friend request? This action cannot be undone."} %>
        <% elsif current_user != @user && !@pending && !@received && @friend %>
            <%= button_to "Remove friend", friends_destroy_path, :class=>"ui button red",
                method: :delete, params: {user_id: @user.id},
                data: {confirm: "Are you sure you would like to remove this user from your friends? This action cannot be undone."} %>
        <% end %>
    <% end %>
</div>