config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # devise_for :user 
  
  get 'friends', to: 'friends#index'
  get 'users/search', to: 'users#search'
  delete 'friends/destroy'

  resources :friend_requests, except: [:show, :edit, :new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  root to: 'home#index'
  # get 'home/index'
  get 'articles/new', to: 'articles#new'
  get 'articles', to: 'articles#index'
  post 'articles', to: 'articles#create'
  get 'articles/:id', to: 'articles#show', as: 'article'
  patch 'articles/:id', to: 'articles#update'
  delete 'articles/:id', to: 'articles#destroy'
  get 'articles/:id/edit', to: 'articles#edit', as: 'article_edit'

  resources :users, except: [:index] do 
    member do
      get :confirm_email
      get :change_password
      patch :change_password_confirm
    end
  end

  post 'comments/:id/edit', to: 'comments#create'
  get 'comments/:id/edit', to: 'comments#edit', as: 'comment_edit'
  patch 'comments/:id/edit', to: 'comments#update'
  delete 'comments/:id/edit', to: 'comments#destroy'

  resources :groups do 
    resources :group_articles, :path => "articles", :as => "articles"
  end

  resources :group_comments, only: [:create, :edit, :update, :destroy]

  delete 'groups/:id/leave', to: 'groups#leave_group', as: 'leave_group'

end

app/models/group_article.rb
class GroupArticle < ApplicationRecord
    validates :title, :content, presence: true
    validates :title, uniqueness: {:scope => :group_id }
    has_many :group_comments, dependent: :destroy
    belongs_to :user
    belongs_to :group, foreign_key: :group_id
end

app/controllers/group_articles_controller.rb
class GroupArticlesController < ApplicationController
    before_action :set_group#, only: [:index, :new, :create, :show]
    before_action :set_group_article, only: [:show, :edit, :update, :destroy]
    before_action :authorize_group_article, only: [:new, :create]
    # after_action :verify_authorized

    def index
        @articles = @group.group_articles
    end

    def show
        @user = User.find_by_id(@article.user_id)
        @comment = GroupComment.new
        @comments = GroupComment.where(group_article_id: @article.id).includes(:user, :group_article)
    end

    def new
        @article = GroupArticle.new
    end

    def create
        @article = GroupArticle.new(group_article_params)
        @article.user = current_user
        @article.group = @group
        if @article.save
            redirect_to group_article_path(@group, @article), 
            flash: {success: "#{@group.item_name} was created."}
        else
            render 'new'
        end
        
    end

    def edit
    end

    def update
        if @article.update(group_article_params)
            redirect_to group_article_path(@group, @article),
            flash: {success: "#{@article.group.item_name} was updated."}
        else
            render 'edit'
        end
    end

    def destroy
        if @article
            @article.destroy
            redirect_to group_path(@group), flash: {success: "#{@group.item_name} was deleted."}
        else
            render 'show'
        end
    end

private

    def group_article_params
        params.require(:group_article).permit(:title, :content)
    end

    def set_group
        @group = Group.find_by_id(params[:group_id])
        authorize @group, :show_group?
    end

    def set_group_article
        @article = GroupArticle.find_by_id(params[:id])
        authorize @article
    end    

    def authorize_group_article
        authorize GroupArticle
    end

end

app/views/group_articles/_back_group_article.html.erb
<span class="align-right">
    <%= link_to group_article_path(@group, @article) do %>
        <button class="ui gray button">Go back</button>
    <% end %>
</span>

app/views/group_articles/_form.html.erb
<% if @article.errors.any? %>
    <div class="ui error message">
        <ul>
            <% @article.errors.full_messages.each do |e| %>
                <li><%= e %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<%= form_for(@article, url: group_article_path(@group, @article)) do |form| %>
    <div class="ui form">
        <div class="field">
            <%= form.label :title %>
            <%= form.text_field :title, placeholder: "Enter your title here" %>
        </div>

        <div class="field">
            <%= form.label :content %>
            <%= form.text_area :content, {size: "60x10", placeholder: "Enter the contents of your article here"} %>
        </div>

        <% if params[:id] %>
            <%= form.button 'Update', :class=>"ui blue button" %>
        <% else %>
            <%= form.button 'Create', :class=>"ui green button" %>
        <% end %>
    </div>
<% end %>

app/views/group_articles/edit.html.erb
<h2>Edit this <%= @article.group.item_name %>
    <%= render 'shared/back_button', path: group_article_path(@group, @article) %>
</h2>
<%= render :partial => "group_articles/form" %>

app/views/group_articles/new.html.erb
<h2>Create your <%= @group.item_name %>
    <span class="align-right">
        <%= link_to group_path(@group) do %>
            <button class="ui gray button">Go back</button>
        <% end %>
    </span>
</h2>


<% if @article.errors.any? %>
    <div class="ui error message">
        <ul>
            <% @article.errors.full_messages.each do |e| %>
                <li><%= e %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<%= form_for(@article) do |form| %>
    <div class="ui form">
        <div class="field">
            <%= form.label :title %>
            <%= form.text_field :title, placeholder: "Enter your title here", autofocus: true %>
        </div>

        <div class="field">
            <%= form.label :content %>
            <%= form.text_area :content, {size: "60x10", placeholder: "Enter the contents of your article here"} %>
        </div>

        <% if params[:action] == 'edit' %>
            <%= form.button 'Update', :class=>"ui blue button" %>
        <% else %>
            <%= form.button 'Create', :class=>"ui green button" %>
        <% end %>
    </div>
<% end %>

app/views/group_articles/show.html.erb
<h2><%= @article.title %>
    <span class="align-right">
        <%= button_to "Return to #{@group.item_name} List", group_path(@group),
            method: :get, :class=>"ui button gray" %>
    </span>
</h2>

<%= render partial: 'articles/writtenby' %>

<br>
<div class="article-body" style="white-space: pre-wrap;"><%= simple_format(@article.content) %></div>
<br>

<div class="ui divider"></div>

<div>
    <h4>Comments</h4>
    <ul>
        <% if @comments.any? %>
            <% @comments.each do |comment| %>
                <li>
                    <%= comment.content %>
                     – <%= link_to comment.user.username, user_path(comment.user) %>
                    <% if can_edit_delete?(comment.user) %>
                        (
                        <%= link_to 'Edit', edit_group_comment_path(comment) %>
                        | 
                        <%= link_to 'Delete', group_comment_path(comment), 
                            method: :delete, group_article_id: @article.id,
                            data: { confirm: 'Are you sure you want to delete this comment? This action cannot be undone.' } %>
                        )
                    <% end %>
                </li>
            <% end %>
        <% else %>
            <p>No comments yet. Why don't you be the first to comment?</p>
        <% end %>
    </ul>
</div>

<div class="ui divider"></div>

<%= render partial: 'group_comments/form' %>

<% if can_edit_delete?(@user) %>
    <div class="ui divider"></div>
    <%= button_to "Edit this article", edit_group_article_path(@group, @article),
        :class=>"ui button blue", method: :get, params: {action: 'edit'} %>
    <br>
    <%= button_to "Delete this article", group_article_path(@group, @article),
        :class=>"ui button red", method: :delete, 
        data: { confirm: 'Are you sure you want to delete this article? This action cannot be undone.' } %>
<% end %>